// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IServices is an autogenerated mock type for the IServices type
type IServices struct {
	mock.Mock
}

// Hello provides a mock function with given fields: ctx
func (_m *IServices) Hello(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIServices interface {
	mock.TestingT
	Cleanup(func())
}

// NewIServices creates a new instance of IServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIServices(t mockConstructorTestingTNewIServices) *IServices {
	mock := &IServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
