name: Go

on:
  push:
    branches: [ "main", "test" ]

jobs:
  image_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Set Environment Variables
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
        calculatedBranch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        echo "BRANCH=$calculatedBranch" >> $GITHUB_ENV
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: wolifexingo/xuyu:${{ env.BRANCH }}_${{ env.SHORT_SHA }}
